#!/usr/bin/env bash
# checks the NPM package cache for problematic packages
# from https://www.ox.security/blog/npm-packages-compromised/

# to be extended the next time news about compromised NPM packages comes up

set -euo pipefail

packages=(
  backslash@0.2.1
  chalk-template@1.1.1
  supports-hyperlinks@4.1.1
  has-ansi@6.0.1
  simple-swizzle@0.2.3
  color-string@2.1.1
  error-ex@1.3.3
  color-name@2.0.1
  is-arrayish@0.3.3
  slice-ansi@7.1.1
  color-convert@3.1.1
  wrap-ansi@9.0.1
  ansi-regex@6.2.1
  supports-color@10.2.1
  strip-ansi@7.1.1
  chalk@5.6.1
  debug@4.4.2
  ansi-styles@6.2.2
)

echo "Checking npm cache..."
npm_output="$(npm cache ls 2>/dev/null || true)"

found=false
for p in "${packages[@]}"; do
  name=${p%@*}
  ver=${p#*@}
  if grep -q "${name}-${ver}" <<<"$npm_output"; then
    echo "• $p"
    found=true
  fi
done

$found || echo "(none)"

