#!/usr/bin/env bash
# checks the NPM package cache for problematic packages
# based on https://www.ox.security/blog/npm-packages-compromised/

set -euo pipefail

OPENQA_HELPER_DIR=${OPENQA_HELPER_DIR:-$OPENQA_BASEDIR/repos/openQA-helper}
source "$OPENQA_HELPER_DIR/lib/problematic-npm-packages.sh"

echo "Checking npm cache..."
npm_output="$(npm cache ls 2>/dev/null || true)"

found=false
for p in "${packages[@]}"; do
  name=${p%@*}
  ver=${p##*@}
  if grep -q "${name}-${ver}" <<<"$npm_output"; then
    echo "• $p"
    found=true
  fi
done

$found || echo "(none)"

