#!/bin/sh
# checks the list of installed NPM packages for problematic packages
# from https://www.ox.security/blog/npm-packages-compromised/

# to be extended the next time news about compromised NPM packages comes up

pkgs="backslash@0.2.1 chalk@5.6.1 chalk-template@1.1.1 color-convert@3.1.1 \
color-name@2.0.1 color-string@2.1.1 wrap-ansi@9.0.1 supports-hyperlinks@4.1.1 \
strip-ansi@7.1.1 slice-ansi@7.1.1 simple-swizzle@0.2.3 is-arrayish@0.3.3 \
error-ex@1.3.3 ansi-regex@6.2.1 ansi-styles@6.2.2 supports-color@10.2.1 debug@4.4.2"

for p in $pkgs; do
  pkg=${p%@*}; vuln=${p#*@}
  echo "$pkg (vuln: $vuln)"
  npm ls "$pkg" --all --depth=Infinity 2>/dev/null \
    | grep -o "$pkg@[^ ]*" | cut -d@ -f2 | sort -u | sed 's/^/  - /' \
    || echo "  - Not installed"
done

