#!/bin/sh
# checks the list of installed NPM packages for problematic packages
# based on https://www.ox.security/blog/npm-packages-compromised/

OPENQA_HELPER_DIR=${OPENQA_HELPER_DIR:-$OPENQA_BASEDIR/repos/openQA-helper}
source "$OPENQA_HELPER_DIR/lib/problematic-npm-packages.sh"

for p in "${packages[@]}"; do
  pkg=${p%@*}; vuln=${p##*@}
  echo "$pkg (vuln: $vuln)"
  npm ls "$pkg" --all --depth=Infinity 2>/dev/null \
    | grep -o "$pkg@[^ ]*" | cut -d@ -f2 | sort -u | sed 's/^/  - /' \
    || echo "  - Not installed"
  # also check package-lock.json for any version of the package (should be improved for better output and consider version)
  grep "$pkg" package-lock.json
done
