#!/bin/bash
set -e

db_base_name=$1
db_branch_name=$2

if ! [[ $db_base_name ]] || ! [[ $db_branch_name ]]; then
    echo "Updates SQL statements for migration and renews the specified devel branch database based on the specified base database"
    echo "usage: $0 base_db devel_branch_db"
    echo "eg. openqa-local{,-developer-session}"
    exit 1
fi

echo "Update SQL statements for db init and migration"
openqa-start initdb --prepare_init --force
openqa-start upgradedb --prepare_upgrades --force

echo "Dropping previous devel DB"
if ! sudo sudo -u postgres dropdb "$db_branch_name"; then
    echo "$db_branch_name doesn't exist anyways"
fi

echo "Creating new devel DB"
sudo sudo -u postgres createdb -O "$USER" -T "$db_base_name" "$db_branch_name"
