#!/bin/bash
set -e
cd "$OPENQA_BASEDIR/repos/openQA"

what=$1
shift

declare -A shortcuts=(
    [wu]=webui
    [ws]=websockets
    [ra]=resource-allocator
    [sc]=scheduler
    [wo]=worker
    [cj]=clone-job
)
what=${shortcuts[$what]:-$what}

if [[ $what == webui ]]; then
    script/openqa daemon "$@"
elif [[ $what == worker ]]; then
    script/worker --isotovideo "$OPENQA_BASEDIR/repos/os-autoinst/isotovideo" --host localhost:9526 --instance 1 --no-cleanup --verbose --apikey $OPENQA_KEY --apisecret $OPENQA_SECRET "$@"
elif [[ $what == clone-job ]]; then
    script/clone_job.pl --dir "$OPENQA_BASEDIR/openqa/share/factory" --host http://localhost:9526 --from https://openqa.opensuse.org "$@"
else
    script/openqa-"$what" "$@"
fi
