#!/bin/bash
set -e

db_name=$1
dump_path=$2

if ! [[ $db_name ]] || ! [[ $dump_path ]]; then
    echo "Imports a database dump, replaces the existing database"
    echo "usage: $0 db_name dump_path"
    echo "eg. openqa-osd 2018-07-03.dump"
    exit 1
fi

[[ -f $dump_path ]] || dump_path="$OPENQA_BASEDIR/sql-dumps/$dump_path"
if ! [[ -f $dump_path ]]; then
    echo "dump $dump_path not found"
    exit 1
fi

sudo sudo -u postgres createdb -O "$USER" "$db_name"
pg_restore -c -d "$db_name" "$dump_path"
