#!/bin/bash
parent_dir=${PWD%/*}
[[ $parent_dir == "$OPENQA_BASEDIR/repos" ]] && OPENQA_CHECKOUT=${OPENQA_CHECKOUT:-${PWD##*/}}
cd "$OPENQA_BASEDIR/repos/${OPENQA_CHECKOUT:-openQA}"
[[ $1 == 't/testinstance' ]] && basedir="$OPENQA_BASEDIR/repos/openQA/t/data" || basedir=
[[ $NOT_HEADLESS ]] || echo 'Note: use NOT_HEADLESS=1 to watch execution of UI tests.'
if ! [[ -e /dev/shm/tpg ]]; then
    echo 'Start database for test with openqa-pg first.'
    exit -1
fi
echo 'Note: one might use "psql --host=/dev/shm/tpg openqa_test" to investigate the database used during this test'

source "$OPENQA_BASEDIR/repos/openQA-helper/lib/customize_dirs.sh"

export HEAVY=1
export SCHEDULER_FULLSTACK=1
export DEVELOPER_FULLSTACK=1
export FULLSTACK=1
export LANGUAGE= LANG=C.utf8
export TEST_PG='DBI:Pg:dbname=openqa_test;host=/dev/shm/tpg'
export OPENQA_BASEDIR="$basedir"
export OPENQA_CONFIG=
export OPENQA_SCHEDULER_STARVATION_PROTECTION_PRIORITY_OFFSET=10
export OPENQA_SCHEDULER_HOST=
export OPENQA_WEB_SOCKETS_HOST=
#export MOJO_PORT=${MOJO_PORT:-12345}
export PROVE_ARGS=${PROVE_ARGS:--l -v}
export OPENQA_TEST_TIMEOUT_DISABLE=1

echo "Using openQA checkout: $PWD"
echo prove $PROVE_ARGS "$@"
prove $PROVE_ARGS "$@"
