#!/bin/bash
set -e

if ! [[ -d $OPENQA_BASEDIR ]]; then
    echo 'Please set $OPENQA_BASEDIR to a valid directory.'
    exit 1
fi

gh_user=$1
if ! [[ $gh_user ]]; then
    echo 'Please pass your GitHub user name as first arg.'
    exit 2
fi

mkdir -p "$OPENQA_BASEDIR/repos"
cd "$OPENQA_BASEDIR/repos"

# define function to clone repo and add fork
function clone_repo() {
    local repo_name=${1}
    local repo_as=${2:-$repo_name}
    local repo_url="https://github.com/os-autoinst/$repo_name"
    
    if [[ -d $repo_name ]]; then
        echo "Skipping $repo_name; already exists."
        return 0
    fi
    
    git clone "$repo_url" "$repo_as"
    pushd "$repo_as"
    git remote add "$gh_user" "git@github.com:$gh_user/$repo_name.git"
    git remote update
    popd
}

# clone openQA and create required directories for config and test data
clone_repo openQA
mkdir -p "$OPENQA_BASEDIR/config"
cp -r "$OPENQA_BASEDIR/repos/openQA/etc/"* "$OPENQA_BASEDIR/config"
mkdir -p "$OPENQA_BASEDIR/openqa/"{db,testresults,share}
mkdir -p "$OPENQA_BASEDIR/openqa/share/factory/"{iso,other}

# clone os-autoinst
clone_repo os-autoinst
# preserve a clean copy of os-autoinst
cp -r "$OPENQA_BASEDIR/repos/os-autoinst"{,-clean}

# clone tests for openSUSE
mkdir -p "$OPENQA_BASEDIR/openqa/share/tests"
cd "$OPENQA_BASEDIR/openqa/share/tests"
clone_repo os-autoinst-distri-opensuse opensuse
ln -s opensuse sle

# create symlinks for tidy
cd "$OPENQA_BASEDIR/openqa/share/tests/opensuse"
pushd tools
ln -s ../../../../../repos/os-autoinst/tools/tidy
popd
ln -s ../../../../repos/os-autoinst/.perltidyrc

# clone needles for openSUSE (yes, this is a subdirectory in our previous checkout)
mkdir -p "$OPENQA_BASEDIR/openqa/share/tests/opensuse/products/opensuse"
cd "$OPENQA_BASEDIR/openqa/share/tests/opensuse/products/opensuse"
clone_repo os-autoinst-needles-opensuse needles
# note: needles for SLE not incluced, checkout from internal repo manually
