#!/bin/bash
set -e

zypper ar https://download.opensuse.org/repositories/devel:/openQA/openSUSE_Tumbleweed devel-openqa
zypper ar https://download.opensuse.org/repositories/devel:/languages:/perl/openSUSE_Tumbleweed devel-perl
zypper ar https://download.opensuse.org/repositories/devel:/languages:/perl:/CPAN-M/openSUSE_Tumbleweed devel-perl-m
zypper in openQA-{client,common,local-db,worker} \
          automake \
          autoconf \
          gcc-c++ \
          os-autoinst \
          opencv-devel \
          libtool \
          qemu-tools \
          chromedriver \
          postgresql-server \
          ShellCheck \
          'rubygem(sass)' \
          'pkgconfig(fftw3)' \
          'pkgconfig(libpng)' \
          'pkgconfig(sndfile)' \
          'pkgconfig(theoraenc)' \
          'perl(Module::CPANfile)' \
          'perl(Mojo::RabbitMQ::Client)' \
          'perl(Mojolicious::Plugin::NYTProf)' \
          'perl(Perl::Critic)' \
          'perl(Perl::Tidy)' \
          'perl(Selenium::Remote::Driver)' \
          'perl(Test::Strict)' \
          'perl(Test::MockObject)' \
          'perl(Test::Warnings)' \
          'perl(DBIx::Class::DeploymentHandler)' \
          'perl(SQL::SplitStatement)' \
          'perl(Mojolicious::Plugin::AssetPack)' \
          'perl(DBIx::Class)' \
          'perl(Minion)' \
          'perl(XML::Writer)' \
          'perl(Devel::NYTProf)'
