#!/bin/bash
set -e

db_base_name=$1
db_branch_name=$2

if ! [[ $db_base_name ]] || ! [[ $db_branch_name ]]; then
    echo "Creates a new db for development based on another db, configures openQA to use it"
    echo "usage: $0 base_db devel_branch_db"
    echo "eg. openqa-local{,-developer-session}"
    exit 1
fi

echo "Clean previous devel DB"
if ! sudo sudo -u postgres dropdb "$db_branch_name"; then
    echo "$db_branch_name doesn't exist anyways"
fi

echo "Creating new devel DB"
sudo sudo -u postgres createdb -O "$USER" -T "$db_base_name" "$db_branch_name"

echo "Apply config"
echo "[test]
dsn = dbi:SQLite:dbname=:memory:
on_connect_call = use_foreign_keys
on_connect_do = PRAGMA synchronous = OFF
sqlite_unicode = 1

[production]
dsn = dbi:Pg:dbname=$db_branch_name
" > "$OPENQA_CONFIG/database-$db_branch_name.ini"
openqa-switchdb "$db_branch_name"
