#!/bin/bash
set -e

if ! [[ -d $OPENQA_BASEDIR ]]; then
    echo 'Please set $OPENQA_BASEDIR to a valid directory.'
    exit 1
fi

gh_user=$1
if ! [[ $gh_user ]]; then
    echo 'Please pass your GitHub user name as first arg.'
    exit 2
fi

mkdir -p "$OPENQA_BASEDIR/repos"
cd "$OPENQA_BASEDIR/repos"

# include function to clone repo and add fork
source "$OPENQA_BASEDIR/repos/openQA-helper/lib/clone_repo.sh"

# clone openQA and create required directories for config and test data
clone_repo openQA
mkdir -p "$OPENQA_BASEDIR/config"
cp -r "$OPENQA_BASEDIR/repos/openQA/etc/openqa/"* --target-directory="$OPENQA_BASEDIR/config"
mkdir -p "$OPENQA_BASEDIR/openqa/"{db,testresults,share}
mkdir -p "$OPENQA_BASEDIR/openqa/share/factory/"{iso,other}
mkdir -p "$OPENQA_BASEDIR/openqa/worker/"{share,cache}

# clone os-autoinst
clone_repo os-autoinst

# clone further repos
clone_repo os-autoinst-scripts
ln -s os-autoinst-scripts scripts

# clone tests for openSUSE
mkdir -p "$OPENQA_BASEDIR/openqa/share/tests"
cd "$OPENQA_BASEDIR/openqa/share/tests"
clone_repo os-autoinst-distri-opensuse opensuse
ln -s opensuse sle

# create symlinks for tidy
cd "$OPENQA_BASEDIR/openqa/share/tests/opensuse"
ln -rs "$OPENQA_BASEDIR/repos/os-autoinst" "os-autoinst"
for tool in lib absolutize tidy; do
    ln -rs "$OPENQA_BASEDIR/repos/os-autoinst/tools/$tool" "tools/$tool"
done

# clone needles for openSUSE (yes, this is a subdirectory in our previous checkout)
mkdir -p "$OPENQA_BASEDIR/openqa/share/tests/opensuse/products/opensuse"
cd "$OPENQA_BASEDIR/openqa/share/tests/opensuse/products/opensuse"
clone_repo os-autoinst-needles-opensuse needles
# note: needles for SLE not incluced, checkout from internal repo manually
