#!/bin/bash
set -e
cd "$OPENQA_BASEDIR/repos/openQA"

what=$1
shift

declare -A shortcuts=(
    [wu]=webui
    [lv]=live
    [wu2]=webui2
    [ws]=websockets
    [ra]=resource-allocator
    [sc]=scheduler
    [wo]=worker
    [wc]=workercache
    [wcm]=workercache-minion
    [cj]=clone-job
    [jc]=clone-job
    [job-clone]=job-clone
)
what=${shortcuts[$what]:-$what}

function start_script {
    echo "$@"
    if [[ $PERL_DEBUGGER_GUI ]]; then
        perl -d:ptkdb "$@"
    elif [[ $PERL_ARGS ]]; then
        perl $PERL_ARGS "$@"
    else
        "$@"
    fi
}

if [[ $what == webui ]]; then
    start_script script/openqa daemon "$@"
elif [[ $what == webui2 ]]; then
    start_script script/openqa daemon -l http://127.0.0.1:12345 "$@"
elif [[ $what == gru ]]; then
    start_script script/openqa gru "$@"
elif [[ $what == live ]]; then
    start_script script/openqa-livehandler daemon "$@"
elif [[ $what == client ]]; then
    start_script script/client --host localhost:9526 --apikey $OPENQA_KEY --apisecret $OPENQA_SECRET "$@"
elif [[ $what == worker ]]; then
    start_script script/worker --isotovideo "$OPENQA_BASEDIR/repos/os-autoinst/isotovideo" --host localhost:9526 --instance 1 --no-cleanup --verbose --apikey $OPENQA_KEY --apisecret $OPENQA_SECRET "$@"
elif [[ $what == workercache ]]; then
    start_script script/openqa-workercache daemon "$@"
elif [[ $what == workercache-minion ]]; then
    start_script script/openqa-workercache minion worker "$@"
elif [[ $what == clone-job ]] || [[ $what == job-clone ]]; then
    start_script script/clone_job.pl --dir "$OPENQA_BASEDIR/openqa/share/factory" --apikey $OPENQA_KEY --apisecret $OPENQA_SECRET --host localhost:9526 "$@"
elif [[ $what == all ]]; then
    source "$OPENQA_BASEDIR/repos/openQA-helper/lib/tabs.sh"
    sessions=(
        openQA-webui               'wu'
        openQA-live                'lv'
        openQA-websockets          'ws'
        openQA-resource-allocator  'ra'
        openQA-scheduler           'sc'
        openQA-worker1             'wo'
    )
    start_sessions ${sessions[@]}
elif [[ -x script/openqa-$what ]]; then
    start_script script/openqa-"$what" "$@"
elif [[ -x script/$what ]]; then
    start_script script/"$what" "$@"
else
    echo "Script \"$what\" not found."
    exit -1
fi
