#!/bin/bash
cd "$OPENQA_BASEDIR/repos/openQA"
CONTAINER_NAME=${CONTAINER_NAME:-openqa-testsuite}

# read docker options and test command
docker_options=()
test_command=()
read=docker_options
not_headless=
for arg in "$@"; do
    if [[ $arg == -- ]]; then
        read=test_command
    else
        if [[ $read == docker_options ]]; then
            docker_options+=("$arg")
        elif [[ $read == test_command ]]; then
            test_command+=("$arg")
        fi
    fi
done

# set default test command
[[ $test_command ]] || test_command=(make docker-tests)

# keep a bash open so we can investigate failures easier
test_command+=(';' 'bash')

# use host X
XSOCK=/tmp/.X11-unix:/tmp/.X11-unix:rw
XAUTH=/tmp/.docker.xauth
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
xhost +local:root

for cmd in echo sudo; do
    $cmd docker run \
        --rm -ti \
        --name "$CONTAINER_NAME" \
        --cap-add SYS_ADMIN \
        -v "$XSOCK" -v "$XAUTH" -e XAUTHORITY="$XAUTH" -e DISPLAY="$DISPLAY" --device /dev/dri --device /dev/snd \
        -e CUSTOM_OS_AUTOINST=1 \
        -v "$OPENQA_BASEDIR/repos/openQA:/opt/openqa" \
        -v "$OPENQA_BASEDIR/repos/os-autoinst:/opt/os-autoinst" \
        -v /var/run/dbus:/var/run/dbus \
        "${docker_options[@]}" registry.opensuse.org/devel/openqa/containers/openqa_dev "${test_command[@]}"
done

xhost -local:root
