#!/bin/bash
set -e

if ! [[ -d $OPENQA_BASEDIR ]]; then
    echo 'Please set $OPENQA_BASEDIR to a valid directory.'
    exit 1
fi

cd "$OPENQA_BASEDIR/repos"

function update_repo() {
    pushd "$1"

    # get current branch
    local branch_name=$(git symbolic-ref -q HEAD)
    local branch_name=${branch_name##refs/heads/}
    local branch_name=${branch_name:-DETACHED}

    # get new stuff from everywhere
    git remote update

    # get in clean state, we should never have any commits on local master anyways
    [[ $branch_name == master ]] && git reset --hard origin/master
    
    # run configure/make
    if [[ -f configure ]]; then
        if ! ./configure; then
            libtoolize --force
            aclocal
            automake --force-missing --add-missing
            autoconf
            ./configure
        fi
        make
    fi
    
    popd
}

update_repo "$OPENQA_BASEDIR/repos/openQA"
update_repo "$OPENQA_BASEDIR/repos/os-autoinst"
update_repo "$OPENQA_BASEDIR/openqa/share/tests/opensuse"
update_repo "$OPENQA_BASEDIR/openqa/share/tests/opensuse/products/opensuse/needles"
